/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.ws.rs.ext.Provider;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * StInvestigator generated by hbm2java
 */
@Provider
@XmlRootElement(name="investigator")
public class StInvestigator implements java.io.Serializable {

	private Integer investigatorid;
	private String investAbbreviation;
	private String investName;
	private boolean status = true;

	private Set<AuthUserBean> setAuthUserBean = new HashSet<AuthUserBean>(0);

	private Set<StLabStudy> stLabStudies = new HashSet<StLabStudy>(0);
	public StInvestigator() {
	}

	public StInvestigator(String investAbbreviation, String investName,
			Set<StLabStudy> stLabStudies, Set<AuthUserBean> stAuthUserBean) {
		this.investAbbreviation = investAbbreviation;
		this.investName = investName;
		this.stLabStudies = stLabStudies;
		this.setAuthUserBean = stAuthUserBean;
	}

	public Integer getInvestigatorid() {
		return this.investigatorid;
	}

	public void setInvestigatorid(Integer investigatorid) {
		this.investigatorid = investigatorid;
	}

	public String getInvestAbbreviation() {
		return this.investAbbreviation;
	}

	public void setInvestAbbreviation(String investAbbreviation) {
		this.investAbbreviation = investAbbreviation;
	}

	public String getInvestName() {
		return this.investName;
	}

	public void setInvestName(String investName) {
		this.investName = investName;
	}

	@XmlTransient
	public Set<StLabStudy> getStLabStudies() {
		return this.stLabStudies;
	}

	public void setStLabStudies(Set<StLabStudy> stLabStudies) {
		this.stLabStudies = stLabStudies;
	}

	public Set<AuthUserBean> getSetAuthUserBean() {
		return setAuthUserBean;
	}

	public void setSetAuthUserBean(Set<AuthUserBean> setAuthUserBean) {
		this.setAuthUserBean = setAuthUserBean;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
