/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.ws.rs.ext.Provider;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * StLabStudy generated by hbm2java
 */

@Provider
@XmlRootElement(name="study")
public class StLabStudy implements java.io.Serializable {

	private Integer labstudyid;
	private Integer projectId;
	private StProject stProject;
	private String title;
	private String objective;
	private Date startdate;
	private Date enddate;
	private Character platetype;
	private Integer platesize;
	private Integer numindiv;
	private Integer numofplates;
	private String prefix;
	private String pathLastFileLoaded;
	private String nameLastFileLoaded;
	private Integer numcontrols;
	private Set<StSampleDetail> stSampleDetails = new HashSet<StSampleDetail>(0);
	private StInvestigator stInvestigator;
	public StLabStudy() {
	}


	public StLabStudy(	StProject stProject, String title, String objective,
			Date startdate, Date enddate, Character platetype,
			Integer platesize, Integer numindiv, Integer numofplates,
			String prefix, String pathLastFileLoaded,
			String nameLastFileLoaded, Integer numcontrols,
			Set<StSampleDetail> stSampleDetails) {
		this.stProject = stProject;
		this.title = title;
		this.objective = objective;
		this.startdate = startdate;
		this.enddate = enddate;
		this.platetype = platetype;
		this.platesize = platesize;
		this.numindiv = numindiv;
		this.numofplates = numofplates;
		this.prefix = prefix;
		this.pathLastFileLoaded = pathLastFileLoaded;
		this.nameLastFileLoaded = nameLastFileLoaded;
		this.numcontrols = numcontrols;
		this.stSampleDetails = stSampleDetails;
	}

	public Integer getLabstudyid() {
		return this.labstudyid;
	}

	public void setLabstudyid(Integer labstudyid) {
		this.labstudyid = labstudyid;
	}


	@XmlTransient
	public StProject getStProject() {
		return this.stProject;
	}

	public void setStProject(StProject stProject) {
		this.stProject = stProject;
	}

	@XmlElement(name="studyName")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getObjective() {
		return this.objective;
	}

	public void setObjective(String objective) {
		this.objective = objective;
	}

	@XmlTransient
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@XmlTransient
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@XmlTransient
	public Character getPlatetype() {
		return this.platetype;
	}

	public void setPlatetype(Character platetype) {
		this.platetype = platetype;
	}

	@XmlTransient
	public Integer getPlatesize() {
		return this.platesize;
	}

	public void setPlatesize(Integer platesize) {
		this.platesize = platesize;
	}

	public Integer getNumindiv() {
		return this.numindiv;
	}

	public void setNumindiv(Integer numindiv) {
		this.numindiv = numindiv;
	}

	@XmlTransient
	public Integer getNumofplates() {
		return this.numofplates;
	}

	public void setNumofplates(Integer numofplates) {
		this.numofplates = numofplates;
	}

	@XmlTransient
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@XmlTransient
	public String getPathLastFileLoaded() {
		return this.pathLastFileLoaded;
	}

	public void setPathLastFileLoaded(String pathLastFileLoaded) {
		this.pathLastFileLoaded = pathLastFileLoaded;
	}

	@XmlTransient
	public String getNameLastFileLoaded() {
		return this.nameLastFileLoaded;
	}

	public void setNameLastFileLoaded(String nameLastFileLoaded) {
		this.nameLastFileLoaded = nameLastFileLoaded;
	}

	@XmlTransient
	public Integer getNumcontrols() {
		return this.numcontrols;
	}

	public void setNumcontrols(Integer numcontrols) {
		this.numcontrols = numcontrols;
	}

	@XmlTransient
	public Set<StSampleDetail> getStSampleDetails() {
		return this.stSampleDetails;
	}

	public void setStSampleDetails(Set<StSampleDetail> stSampleDetails) {
		this.stSampleDetails = stSampleDetails;
	}

	@XmlTransient
	public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public StInvestigator getStInvestigator() {
		return stInvestigator;
	}


	public void setStInvestigator(StInvestigator stInvestigator) {
		this.stInvestigator = stInvestigator;
	}

}
