/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StLocation generated by hbm2java
 */
public class StLocation implements java.io.Serializable {

	private Integer locationid;
	private String locationName;
	private String locationDescription;
	private Set<StSampleDetail> stSampleDetails = new HashSet<StSampleDetail>(0);
	private Set<StLabStudy> stLabStudies = new HashSet<StLabStudy>(0);

	public StLocation() {
	}

	public StLocation(String locationName, String locationDescription,
			Set<StSampleDetail> stSampleDetails, Set<StLabStudy> stLabStudies) {
		this.locationName = locationName;
		this.locationDescription = locationDescription;
		this.stSampleDetails = stSampleDetails;
		this.stLabStudies = stLabStudies;
	}

	public Integer getLocationid() {
		return this.locationid;
	}

	public void setLocationid(Integer locationid) {
		this.locationid = locationid;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getLocationDescription() {
		return this.locationDescription;
	}

	public void setLocationDescription(String locationDescription) {
		this.locationDescription = locationDescription;
	}

	public Set<StSampleDetail> getStSampleDetails() {
		return this.stSampleDetails;
	}

	public void setStSampleDetails(Set<StSampleDetail> stSampleDetails) {
		this.stSampleDetails = stSampleDetails;
	}

	public Set<StLabStudy> getStLabStudies() {
		return this.stLabStudies;
	}

	public void setStLabStudies(Set<StLabStudy> stLabStudies) {
		this.stLabStudies = stLabStudies;
	}


}
