/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * StOrganism generated by hbm2java
 */
public class StOrganism implements java.io.Serializable {

	private Integer organismid;
	private String organismName;

	private Set<StLabStudy> stLabStudies = new HashSet<StLabStudy>(0);
	private Set<AuthUserBean> stUserVersions = new HashSet<AuthUserBean>(0);

	public StOrganism() {
	}

	public StOrganism(String organismName,
			Set<StLabStudy> stLabStudies) {
		this.organismName = organismName;
		this.stLabStudies = stLabStudies;
	}

	public Integer getOrganismid() {
		return this.organismid;
	}

	public void setOrganismid(Integer organismid) {
		this.organismid = organismid;
	}

	public String getOrganismName() {
		return this.organismName;
	}

	public void setOrganismName(String organismName) {
		this.organismName = organismName;
	}


	public Set<StLabStudy> getStLabStudies() {
		return this.stLabStudies;
	}

	public void setStLabStudies(Set<StLabStudy> stLabStudies) {
		this.stLabStudies = stLabStudies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stOrganism")
	public Set<AuthUserBean> getStUserVersions() {
		return this.stUserVersions;
	}

	public void setStUserVersions(Set<AuthUserBean> stUserVersions) {
		this.stUserVersions = stUserVersions;
	}
}
