/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;

import javax.xml.bind.annotation.XmlElement;

// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * StSampleid generated by hbm2java
 */
public class StSampleid implements java.io.Serializable {

	private Integer idsample;
	private Integer projectid;
	private Integer gid;
	private Integer nplant;
	private Integer locationid;
	private Integer seasonid;
	private Integer sampleid;

	public StSampleid() {
	}

	public StSampleid(Integer projectid, Integer gid, Integer nplant,
			Integer locationid, Integer seasonid, Integer sampleid) {
		this.projectid = projectid;
		this.gid = gid;
		this.nplant = nplant;
		this.locationid = locationid;
		this.seasonid = seasonid;
		this.sampleid = sampleid;
	}

	public Integer getIdsample() {
		return this.idsample;
	}

	public void setIdsample(Integer idsample) {
		this.idsample = idsample;
	}

	public Integer getProjectid() {
		return this.projectid;
	}

	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

@XmlElement(name="pedigree")
	public Integer getNplant() {
		return this.nplant;
	}

	public void setNplant(Integer nplant) {
		this.nplant = nplant;
	}

	public Integer getLocationid() {
		return this.locationid;
	}

	public void setLocationid(Integer locationid) {
		this.locationid = locationid;
	}

	public Integer getSeasonid() {
		return this.seasonid;
	}

	public void setSeasonid(Integer seasonid) {
		this.seasonid = seasonid;
	}

	public Integer getSampleid() {
		return this.sampleid;
	}

	public void setSampleid(Integer sampleid) {
		this.sampleid = sampleid;
	}

}
