/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.ws.rs.ext.Provider;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * StSampleDetail generated by hbm2java
 */

@Provider
@XmlRootElement(name="sample")
public class StSampleDetail implements java.io.Serializable {

	private Integer studysampleid;
	private Integer studyId;
	private StSeason stSeason;
	private StLabStudy stLabStudy;
	private StLocation stLocation;
	private Integer breedergid;
	private Integer sampleid;
	private Integer entryNo;
	private Integer nplanta;
	private String nval;
	private String platename;
	private String plateloc;
	private Character selforsend;
	private Date lastmovdate;
	private String specie;
	private String priority;
	private String controltype;
	private String sampleName;

	public StSampleDetail() {
	}

	public StSampleDetail(StLabStudy stLabStudy) {
		this.stLabStudy = stLabStudy;
	}

	public StSampleDetail(StSeason stSeason, StLabStudy stLabStudy,
			StLocation stLocation,
			Integer breedergid, Integer sampleid, Integer entryNo,
			Integer nplanta, String nval, String platename, String plateloc,
			Character selforsend, Date lastmovdate, String specie,
			String priority, String controltype) {
		this.stSeason = stSeason;
		this.stLabStudy = stLabStudy;
		this.stLocation = stLocation;
		this.breedergid = breedergid;
		this.sampleid = sampleid;
		this.entryNo = entryNo;
		this.nplanta = nplanta;
		this.nval = nval;
		this.platename = platename;
		this.plateloc = plateloc;
		this.selforsend = selforsend;
		this.lastmovdate = lastmovdate;
		this.specie = specie;
		this.priority = priority;
		this.controltype = controltype;
	}

	public Integer getStudysampleid() {
		return this.studysampleid;
	}

	public void setStudysampleid(Integer studysampleid) {
		this.studysampleid = studysampleid;
	}

	@XmlTransient
	public StSeason getStSeason() {
		return this.stSeason;
	}

	public void setStSeason(StSeason stSeason) {
		this.stSeason = stSeason;
	}

	@XmlTransient
	public StLabStudy getStLabStudy() {
		return this.stLabStudy;
	}

	public void setStLabStudy(StLabStudy stLabStudy) {
		this.stLabStudy = stLabStudy;
	}


	@XmlTransient
	public StLocation getStLocation() {
		return this.stLocation;
	}

	public void setStLocation(StLocation stLocation) {
		this.stLocation = stLocation;
	}

	@XmlElement(name="gid")
	public Integer getBreedergid() {
		return this.breedergid;
	}

	public void setBreedergid(Integer breedergid) {
		this.breedergid = breedergid;
	}

	public Integer getSampleid() {
		return this.sampleid;
	}

	public void setSampleid(Integer sampleid) {
		this.sampleid = sampleid;
	}

	@XmlTransient
	public Integer getEntryNo() {
		return this.entryNo;
	}

	public void setEntryNo(Integer entryNo) {
		this.entryNo = entryNo;
	}

	@XmlTransient
	public Integer getNplanta() {
		return this.nplanta;
	}

	public void setNplanta(Integer nplanta) {
		this.nplanta = nplanta;
	}

	@XmlElement(name="pedigree")
	public String getNval() {
		return this.nval;
	}

	public void setNval(String nval) {
		this.nval = nval;
	}

	@XmlElement(name="populationName")
	public String getPlatename() {
		return this.platename;
	}

	public void setPlatename(String platename) {
		this.platename = platename;
	}

	@XmlTransient
	public String getPlateloc() {
		return this.plateloc;
	}

	public void setPlateloc(String plateloc) {
		this.plateloc = plateloc;
	}

	@XmlTransient
	public Character getSelforsend() {
		return this.selforsend;
	}

	public void setSelforsend(Character selforsend) {
		this.selforsend = selforsend;
	}

	@XmlTransient
	public Date getLastmovdate() {
		return this.lastmovdate;
	}

	public void setLastmovdate(Date lastmovdate) {
		this.lastmovdate = lastmovdate;
	}

	@XmlTransient
	public String getSpecie() {
		return this.specie;
	}

	public void setSpecie(String specie) {
		this.specie = specie;
	}

	@XmlTransient
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@XmlTransient
	public String getControltype() {
		return this.controltype;
	}

	public void setControltype(String controltype) {
		this.controltype = controltype;
	}

	@XmlTransient
	public Integer getStudyId() {
		return studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}
	
	public String getSampleName(){
		return this.sampleName;
	}
	public void setSampleName(String  sampleName){
		this.sampleName = sampleName;
	}

}
