/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StSeason generated by hbm2java
 */
public class StSeason implements java.io.Serializable {

	private Integer seasonid;
	private String seasonName;
	private String seasonDescription;
	private Set<StLabStudy> stLabStudies = new HashSet<StLabStudy>(0);
	private Set<StSampleDetail> stSampleDetails = new HashSet<StSampleDetail>(0);

	public StSeason() {
	}

	public StSeason(String seasonName, String seasonDescription,
			Set<StLabStudy> stLabStudies, Set<StSampleDetail> stSampleDetails) {
		this.seasonName = seasonName;
		this.seasonDescription = seasonDescription;
		this.stLabStudies = stLabStudies;
		this.stSampleDetails = stSampleDetails;
	}

	public Integer getSeasonid() {
		return this.seasonid;
	}

	public void setSeasonid(Integer seasonid) {
		this.seasonid = seasonid;
	}

	public String getSeasonName() {
		return this.seasonName;
	}

	public void setSeasonName(String seasonName) {
		this.seasonName = seasonName;
	}

	public String getSeasonDescription() {
		return this.seasonDescription;
	}

	public void setSeasonDescription(String seasonDescription) {
		this.seasonDescription = seasonDescription;
	}


	public Set<StLabStudy> getStLabStudies() {
		return this.stLabStudies;
	}

	public void setStLabStudies(Set<StLabStudy> stLabStudies) {
		this.stLabStudies = stLabStudies;
	}

	public Set<StSampleDetail> getStSampleDetails() {
		return this.stSampleDetails;
	}

	public void setStSampleDetails(Set<StSampleDetail> stSampleDetails) {
		this.stSampleDetails = stSampleDetails;
	}

}
