/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.cimmyt.dnast.dto;
// default package
// Generated Apr 23, 2013 11:57:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StTissue generated by hbm2java
 */
public class StTissue implements java.io.Serializable {

	private Integer tissueid;
	private String tissuename;
	private Set<StLabStudy> stLabStudies = new HashSet<StLabStudy>(0);

	public StTissue() {
	}

	public StTissue(String tissuename, Set<StLabStudy> stLabStudies) {
		this.tissuename = tissuename;
		this.stLabStudies = stLabStudies;
	}

	public Integer getTissueid() {
		return this.tissueid;
	}

	public void setTissueid(Integer tissueid) {
		this.tissueid = tissueid;
	}

	public String getTissuename() {
		return this.tissuename;
	}

	public void setTissuename(String tissuename) {
		this.tissuename = tissuename;
	}

	public Set<StLabStudy> getStLabStudies() {
		return this.stLabStudies;
	}

	public void setStLabStudies(Set<StLabStudy> stLabStudies) {
		this.stLabStudies = stLabStudies;
	}

}
