package com.cimmyt.model.bean;

// Generated Nov 26, 2015 4:41:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StFuntions generated by hbm2java
 */
@Entity
@Table(name = "st_funtions")
public class Funtions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstFuntions;
	private String funtionKey;
	private Set<UserFuntions> stUserFuntionses = new HashSet<UserFuntions>(0);

	public Funtions() {
	}

	public Funtions(String funtionKey) {
		this.funtionKey = funtionKey;
	}

	public Funtions(String funtionKey, Set<UserFuntions> stUserFuntionses) {
		this.funtionKey = funtionKey;
		this.stUserFuntionses = stUserFuntionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_funtions", unique = true, nullable = false)
	public Integer getIdstFuntions() {
		return this.idstFuntions;
	}

	public void setIdstFuntions(Integer idstFuntions) {
		this.idstFuntions = idstFuntions;
	}

	@Column(name = "funtion_key", nullable = false, length = 45)
	public String getFuntionKey() {
		return this.funtionKey;
	}

	public void setFuntionKey(String funtionKey) {
		this.funtionKey = funtionKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stFuntions")
	public Set<UserFuntions> getStUserFuntionses() {
		return this.stUserFuntionses;
	}

	public void setStUserFuntionses(Set<UserFuntions> stUserFuntionses) {
		this.stUserFuntionses = stUserFuntionses;
	}

}
