/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StFuntions generated by hbm2java
 */
@Entity
@Table(name = "st_log_type_entity")
@SuppressWarnings("serial")
public class LogTypeEntity implements java.io.Serializable{

	private Integer idLogTypeEntity;
	private String description;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_log_type_entity", unique = true, nullable = false)
	public Integer getIdLogTypeEntity() {
		return idLogTypeEntity;
	}

	public void setIdLogTypeEntity(Integer idLogTypeEntity) {
		this.idLogTypeEntity = idLogTypeEntity;
	}

	@Column(name = "description", nullable = false, length = 150)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
