/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;


import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StMixtureDetail generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="st_mixture_detail")
public class MixtureDetail  implements java.io.Serializable {


     private int mixtureDetailId;
     private Integer season;
     private Integer location;
     private Short plantNumber;
     private Collection<SampleMixture> sampleMixtures =  new ArrayList<SampleMixture>(0);

    public MixtureDetail() {
    }

	
    public MixtureDetail(int mixtureDetailId) {
        this.mixtureDetailId = mixtureDetailId;
    }
    public MixtureDetail(int mixtureDetailId, Integer season, Integer location, Short plantNumber, Set<SampleMixture> sampleMixtures) {
       this.mixtureDetailId = mixtureDetailId;
       this.season = season;
       this.location = location;
       this.plantNumber = plantNumber;
       this.sampleMixtures = sampleMixtures;
    }
    @Id 
    @Column(name="mixtureDetailId", unique=true, nullable=false)
    public int getMixtureDetailId() {
        return this.mixtureDetailId;
    }
    public void setMixtureDetailId(int mixtureDetailId) {
        this.mixtureDetailId = mixtureDetailId;
    }

    
    @Column(name="seasonid")
    public Integer getSeason() {
        return this.season;
    }
    
    public void setSeason(Integer season) {
        this.season = season;
    }

    @Column(name="locationid")
    public Integer getLocation() {
        return this.location;
    }
    
    public void setLocation(Integer location) {
        this.location = location;
    }
    @Column(name="plantNumber", precision=4, scale=0)
    public Short getPlantNumber() {
        return this.plantNumber;
    }
    public void setPlantNumber(Short plantNumber) {
        this.plantNumber = plantNumber;
    }
    @OneToMany(cascade = CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mixtureDetail")
    public Collection<SampleMixture> getSampleMixtures() {
        return this.sampleMixtures;
    }
    public void setSampleMixtures(Collection<SampleMixture> sampleMixtures) {
        this.sampleMixtures = sampleMixtures;
    }
}

