/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StMixtureMethod generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "st_mixture_method")
public class MixtureMethod implements java.io.Serializable {

	private int mixtureMethodId;
	private String description;
	private Set<SampleMixture> sampleMixtures = new HashSet<SampleMixture>(
			0);

	public MixtureMethod() {
	}

	public MixtureMethod(int mixtureMethodId) {
		this.mixtureMethodId = mixtureMethodId;
	}

	public MixtureMethod(int mixtureMethodId, String description,
			Set<SampleMixture> sampleMixtures) {
		this.mixtureMethodId = mixtureMethodId;
		this.description = description;
		this.sampleMixtures = sampleMixtures;
	}

	@Id
	@Column(name = "mixtureMethodId", unique = true, nullable = false)
	public int getMixtureMethodId() {
		return this.mixtureMethodId;
	}

	public void setMixtureMethodId(int mixtureMethodId) {
		this.mixtureMethodId = mixtureMethodId;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mixtureMethod")
	public Set<SampleMixture> getSampleMixtures() {
		return this.sampleMixtures;
	}

	public void setSampleMixtures(Set<SampleMixture> SampleMixtures) {
		this.sampleMixtures = SampleMixtures;
	}

}

