/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

// Generated Apr 18, 2017 10:47:12 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StProgram generated by hbm2java
 */
@Entity
@Table(name = "st_program")
public class Program implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstProgram;
	private Organism organism;
	private String letterCode;
	private String programName;
	private String description;
	private boolean status;

	public Program() {
	}

	public Program(Organism organism, String letterCode,
			String programName, String description, boolean status) {
		this.organism = organism;
		this.letterCode = letterCode;
		this.programName = programName;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_program", unique = true, nullable = false)
	public Integer getIdstProgram() {
		return this.idstProgram;
	}

	public void setIdstProgram(Integer idstProgram) {
		this.idstProgram = idstProgram;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "organismid", nullable = false)
	public Organism getOrganism() {
		return this.organism;
	}

	public void setOrganism(Organism organism) {
		this.organism = organism;
	}

	@Column(name = "letter_code", nullable = false, length = 3)
	public String getLetterCode() {
		return this.letterCode;
	}

	public void setLetterCode(String letterCode) {
		this.letterCode = letterCode;
	}

	@Column(name = "program_name", nullable = false, length = 200)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
