/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

// Generated Apr 18, 2017 10:47:12 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StPurpose generated by hbm2java
 */
@Entity
@Table(name = "st_purpose")
public class Purpose implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstPurpose;
	private Organism organism;
	private String letterCode;
	private String purposeName;
	private String description;
	private boolean status;

	public Purpose() {
	}

	public Purpose(Organism organism, String letterCode,
			String purposeName, String description, boolean status) {
		this.organism = organism;
		this.letterCode = letterCode;
		this.purposeName = purposeName;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_purpose", unique = true, nullable = false)
	public Integer getIdstPurpose() {
		return this.idstPurpose;
	}

	public void setIdstPurpose(Integer idstPurpose) {
		this.idstPurpose = idstPurpose;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "organismid", nullable = false)
	public Organism getOrganism() {
		return this.organism;
	}

	public void setOrganism(Organism organism) {
		this.organism = organism;
	}

	@Column(name = "letter_code", nullable = false, length = 3)
	public String getLetterCode() {
		return this.letterCode;
	}

	public void setLetterCode(String letterCode) {
		this.letterCode = letterCode;
	}

	@Column(name = "purpose_name", nullable = false, length = 200)
	public String getPurposeName() {
		return this.purposeName;
	}

	public void setPurposeName(String purposeName) {
		this.purposeName = purposeName;
	}

	@Column(name = "description", nullable = false, length = 245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
