package com.cimmyt.model.bean;

// Generated Dec 8, 2015 1:06:35 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.cimmyt.dnast.dto.AuthUserBean;

/**
 * StRol generated by hbm2java
 */
@Entity
@Table(name = "st_rol")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstRol;
	private String name;
	private Set<AuthUserBean> stUserVersions = new HashSet<AuthUserBean>(0);

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}

	public Role(String name, Set<AuthUserBean> stUserVersions) {
		this.name = name;
		this.stUserVersions = stUserVersions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_rol", unique = true, nullable = false)
	public Integer getIdstRol() {
		return this.idstRol;
	}

	public void setIdstRol(Integer idstRol) {
		this.idstRol = idstRol;
	}

	@Column(name = "name", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stRole")
	public Set<AuthUserBean> getStUserVersions() {
		return this.stUserVersions;
	}

	public void setStUserVersions(Set<AuthUserBean> stUserVersions) {
		this.stUserVersions = stUserVersions;
	}

}
