/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StSampleMixtureId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class SampleMixtureId implements java.io.Serializable {

	private int sampleid;
	private int mixtureDetailId;

	public SampleMixtureId() {
	}

	public SampleMixtureId(int sampleid, int mixtureDetailId) {
		this.sampleid = sampleid;
		this.mixtureDetailId = mixtureDetailId;
	}

	@Column(name = "sampleid", nullable = false)
	public int getSampleid() {
		return this.sampleid;
	}

	public void setSampleid(int sampleid) {
		this.sampleid = sampleid;
	}

	@Column(name = "mixtureDetailId", nullable = false)
	public int getMixtureDetailId() {
		return this.mixtureDetailId;
	}

	public void setMixtureDetailId(int mixtureDetailId) {
		this.mixtureDetailId = mixtureDetailId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SampleMixtureId))
			return false;
		SampleMixtureId castOther = (SampleMixtureId) other;

		return (this.getSampleid() == castOther.getSampleid())
				&& (this.getMixtureDetailId() == castOther.getMixtureDetailId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSampleid();
		result = 37 * result + this.getMixtureDetailId();
		return result;
	}

}