/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StSampleMixture generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "st_sample_mixture")
public class SampleMixture implements java.io.Serializable {

	private SampleMixtureId id;
	private Integer mixtureMethod;
	private MixtureDetail mixtureDetail;

	public SampleMixture() {
	}

	public SampleMixture(SampleMixtureId id, MixtureDetail mixtureDetail) {
		this.id = id;
		this.mixtureDetail = mixtureDetail;
	}

	public SampleMixture(SampleMixtureId id,
			Integer mixtureMethod, MixtureDetail mixtureDetail) {
		this.id = id;
		this.mixtureMethod = mixtureMethod;
		this.mixtureDetail = mixtureDetail;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sampleid", column = @Column(name = "sampleid", nullable = false)),
			@AttributeOverride(name = "mixtureDetailId", column = @Column(name = "mixtureDetailId", nullable = false )) })
	public SampleMixtureId getId() {
		return this.id;
	}

	public void setId(SampleMixtureId id) {
		this.id = id;
	}

	@Column(name = "mixtureMethodId")
	public Integer getMixtureMethod() {
		return this.mixtureMethod;
	}

	public void setMixtureMethod(Integer mixtureMethod) {
		this.mixtureMethod = mixtureMethod;
	}

	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "mixtureDetailId", nullable = false, insertable = false, updatable = false)
	public MixtureDetail getMixtureDetail() {
		return this.mixtureDetail;
	}

	public void setMixtureDetail(MixtureDetail mixtureDetail) {
		this.mixtureDetail = mixtureDetail;
	}

}

