/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

// Generated Jun 27, 2013 3:14:34 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * StShipmentDetail generated by hbm2java
 */
@Entity
@Table(name = "st_shipment_detail")
@NamedQueries({
    @NamedQuery(name = "ShipmentDetail.findAll", query = "SELECT i FROM ShipmentDetail i")})
public class ShipmentDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -532096178634289335L;
	private int idShipmentDetail;
	private ShipmentSet stShipmentSet;
	private SampleDetail stSampleDetail;

	public ShipmentDetail() {
	}

	public ShipmentDetail(int idShipmentDetail, ShipmentSet stShipmentSet,
			SampleDetail stSampleDetail) {
		this.idShipmentDetail = idShipmentDetail;
		this.stShipmentSet = stShipmentSet;
		this.stSampleDetail = stSampleDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_shipment_detail", unique = true, nullable = false)
	public int getIdShipmentDetail() {
		return this.idShipmentDetail;
	}

	public void setIdShipmentDetail(int idShipmentDetail) {
		this.idShipmentDetail = idShipmentDetail;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_shipment_set", referencedColumnName = "id_shipment_set")
	public ShipmentSet getStShipmentSet() {
		return this.stShipmentSet;
	}

	public void setStShipmentSet(ShipmentSet stShipmentSet) {
		this.stShipmentSet = stShipmentSet;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_study_sampleid", referencedColumnName = "studysampleid")
	public SampleDetail getStSampleDetail() {
		return this.stSampleDetail;
	}

	public void setStSampleDetail(SampleDetail stSampleDetail) {
		this.stSampleDetail = stSampleDetail;
	}

}
