/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

// Generated Jun 27, 2013 3:14:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StShipment generated by hbm2java
 */
@Entity
@Table(name = "st_shipment")
@NamedQueries({
    @NamedQuery(name = "Shipment.findAll", query = "SELECT i FROM Shipment i")})
public class Shipment implements java.io.Serializable {
	private static final long serialVersionUID = 8166630030064129450L;

	private Integer idShipment;
	private Status stStatus;
	private ShipmentSet stShipmentSet;
	private Company stCompany;
	private Date datRegister;
	private Date datSend;
	private Date datReceive;
	private String comment;
	private String trackingNumberLocal;
	private String trackingNumberDelivery;
	private Boolean isSentToKB;

	public Shipment() {
	}

	public Shipment(Status stStatus, ShipmentSet stShipmentSet,
			Company stCompany, Date datRegister) {
		this.stStatus = stStatus;
		this.stShipmentSet = stShipmentSet;
		this.stCompany = stCompany;
		this.datRegister = datRegister;
	}

	public Shipment(Status stStatus, ShipmentSet stShipmentSet,
			Company stCompany, Date datRegister, Date datSend,
			Date datReceive, String comment, String trackingNumberLocal,
			String trackingNumberDelivery) {
		this.stStatus = stStatus;
		this.stShipmentSet = stShipmentSet;
		this.stCompany = stCompany;
		this.datRegister = datRegister;
		this.datSend = datSend;
		this.datReceive = datReceive;
		this.comment = comment;
		this.trackingNumberLocal = trackingNumberLocal;
		this.trackingNumberDelivery = trackingNumberDelivery;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_shipment", unique = true, nullable = false)
	public Integer getIdShipment() {
		return this.idShipment;
	}

	public void setIdShipment(Integer idShipment) {
		this.idShipment = idShipment;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_status", nullable = false, referencedColumnName = "id_status")
	public Status getStStatus() {
		return this.stStatus;
	}

	public void setStStatus(Status stStatus) {
		this.stStatus = stStatus;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_shipment_set", nullable = false, referencedColumnName = "id_shipment_set")
	public ShipmentSet getStShipmentSet() {
		return this.stShipmentSet;
	}

	public void setStShipmentSet(ShipmentSet stShipmentSet) {
		this.stShipmentSet = stShipmentSet;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_company", nullable = false, referencedColumnName = "idCompany")
	public Company getStCompany() {
		return this.stCompany;
	}

	public void setStCompany(Company stCompany) {
		this.stCompany = stCompany;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dat_register", nullable = false, length = 10)
	public Date getDatRegister() {
		return this.datRegister;
	}

	public void setDatRegister(Date datRegister) {
		this.datRegister = datRegister;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dat_send", length = 10)
	public Date getDatSend() {
		return this.datSend;
	}

	public void setDatSend(Date datSend) {
		this.datSend = datSend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dat_receive", length = 10)
	public Date getDatReceive() {
		return this.datReceive;
	}

	public void setDatReceive(Date datReceive) {
		this.datReceive = datReceive;
	}

	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "tracking_number_local")
	public String getTrackingNumberLocal() {
		return this.trackingNumberLocal;
	}

	public void setTrackingNumberLocal(String trackingNumberLocal) {
		this.trackingNumberLocal = trackingNumberLocal;
	}

	@Column(name = "tracking_number_delivery")
	public String getTrackingNumberDelivery() {
		return this.trackingNumberDelivery;
	}

	public void setTrackingNumberDelivery(String trackingNumberDelivery) {
		this.trackingNumberDelivery = trackingNumberDelivery;
	}

	@Column(name = "sent_to_kb")
	public Boolean getIsSentToKB() {
		return isSentToKB;
	}

	public void setIsSentToKB(Boolean isSentToKB) {
		this.isSentToKB = isSentToKB;
	}
	


}
