/*
Copyright 2013 International Maize and Wheat Improvement Center
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package com.cimmyt.model.bean;

// Generated Jun 27, 2013 3:14:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StShipmentSet generated by hbm2java
 */
@Entity
@Table(name = "st_shipment_set")
public class ShipmentSet implements java.io.Serializable {

	private Integer idShipmentSet;
	private Investigator stInvestigator;
	private Date datCreated;
	private String comments;
	private Set<Shipment> stShipments = new HashSet<Shipment>(0);
	private Set<ShipmentDetail> stShipmentDetails = new HashSet<ShipmentDetail>(0);

	public ShipmentSet() {
	}

	public ShipmentSet(Investigator stInvestigator, Date datCreated) {
		this.stInvestigator = stInvestigator;
		this.datCreated = datCreated;
	}

	public ShipmentSet(Investigator stInvestigator, Date datCreated,
			String comments, Set<Shipment> stShipments, Set<ShipmentDetail> stShipmentDetails) {
		this.stInvestigator = stInvestigator;
		this.datCreated = datCreated;
		this.comments = comments;
		this.stShipments = stShipments;
		this.stShipmentDetails = stShipmentDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_shipment_set", unique = true, nullable = false)
	public Integer getIdShipmentSet() {
		return this.idShipmentSet;
	}

	public void setIdShipmentSet(Integer idShipmentSet) {
		this.idShipmentSet = idShipmentSet;
	}

	@ManyToOne(optional = false)
	@JoinColumn(name = "fk_investigator", referencedColumnName = "investigatorid")
	public Investigator getStInvestigator() {
		return this.stInvestigator;
	}

	public void setStInvestigator(Investigator stInvestigator) {
		this.stInvestigator = stInvestigator;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dat_created", nullable = false, length = 10)
	public Date getDatCreated() {
		return this.datCreated;
	}

	public void setDatCreated(Date datCreated) {
		this.datCreated = datCreated;
	}

	@Column(name = "comments", length = 100)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "stShipmentSet")
	public Set<Shipment> getStShipments() {
		return this.stShipments;
	}

	public void setStShipments(Set<Shipment> stShipments) {
		this.stShipments = stShipments;
	}

	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "stShipmentSet")
	public Set<ShipmentDetail> getStShipmentDetails() {
		return this.stShipmentDetails;
	}

	public void setStShipmentDetails(Set<ShipmentDetail> stShipmentDetails) {
		this.stShipmentDetails = stShipmentDetails;
	}

}
