package com.cimmyt.model.bean;

// Generated Nov 26, 2015 4:41:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.cimmyt.dnast.dto.AuthUserBean;

/**
 * StUserFuntions generated by hbm2java
 */
@Entity
@Table(name = "st_user_funtions")
public class UserFuntions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idstUserFuntions;
	private AuthUserBean stUserVersion;
	private Funtions Funtions;

	public UserFuntions() {
	}

	public UserFuntions(AuthUserBean stUserVersion, Funtions stFuntions) {
		this.stUserVersion = stUserVersion;
		this.Funtions = stFuntions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idst_user_funtions", unique = true, nullable = false)
	public Integer getIdstUserFuntions() {
		return this.idstUserFuntions;
	}

	public void setIdstUserFuntions(Integer idstUserFuntions) {
		this.idstUserFuntions = idstUserFuntions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_version_id", nullable = false)
	public AuthUserBean getStUserVersion() {
		return this.stUserVersion;
	}

	public void setStUserVersion(AuthUserBean stUserVersion) {
		this.stUserVersion = stUserVersion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idst_funtions", nullable = false)
	public Funtions getStFuntions() {
		return this.Funtions;
	}

	public void setStFuntions(Funtions stFuntions) {
		this.Funtions = stFuntions;
	}

}
